import { UserItem, UserSummaryStats } from "./types";

export const INITIAL_USER_STATS: UserSummaryStats = {
  totalUsers: 1428,
  activeUsers: 1390,
  staffCount: 48,
  pendingInvitations: 12,
};

export const MOCK_USERS: UserItem[] = [
  {
    id: "1",
    userId: "USR-2026-101",
    name: "Patel Kumar",
    username: "@patel_admin",
    email: "patel@adskill.com",
    role: "Super Admin",
    status: "Active",
    whatsapp: "+14165550100",
    phone: "+1 (416) 555-0100",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    initials: "PK",
    department: "Executive Management",
    createdAt: "Jan 01, 2025",
    lastActive: "Active now",
    assignedCasesCount: 142,
    twoFactorEnabled: true,
    bio: "Chief Executive & Lead Platform Administrator with universal PBAC security rights.",
    activityLogs: [
      {
        id: "act-1",
        action: "Updated PBAC Role Matrix",
        target: "Role: Senior Consultant",
        timestamp: "Today at 11:20 AM",
        ipAddress: "192.168.1.10",
      },
      {
        id: "act-2",
        action: "Approved Milestone Refund",
        target: "Client: #APP-2026-7731",
        timestamp: "Yesterday at 4:15 PM",
        ipAddress: "192.168.1.10",
      },
      {
        id: "act-3",
        action: "Exported Annual Financial Ledger",
        target: "Reports / Aging 2025",
        timestamp: "Sep 08, 2026 at 2:00 PM",
        ipAddress: "192.168.1.10",
      },
    ],
  },
  {
    id: "2",
    userId: "USR-2026-102",
    name: "Sarah Jenkins",
    username: "@sarah_j",
    email: "sarah.jenkins@adskill.com",
    role: "Consultant",
    status: "Active",
    whatsapp: "+447700900123",
    phone: "+44 7700 900123",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    initials: "SJ",
    department: "Legal & Immigration",
    createdAt: "Feb 15, 2025",
    lastActive: "12 mins ago",
    assignedCasesCount: 38,
    twoFactorEnabled: true,
    bio: "Senior Immigration Consultant specializing in UK Student and Global Talent Visas.",
    activityLogs: [
      {
        id: "act-4",
        action: "Submitted Biometrics Verification",
        target: "Client: Maria Gonzales",
        timestamp: "Today at 10:45 AM",
        ipAddress: "82.165.197.1",
      },
      {
        id: "act-5",
        action: "Issued Payment Milestone Reminder",
        target: "Client: #APP-2026-8571",
        timestamp: "Sep 09, 2026 at 5:30 PM",
        ipAddress: "82.165.197.1",
      },
    ],
  },
  {
    id: "3",
    userId: "USR-2026-103",
    name: "Michael Brooks",
    username: "@mbrooks_cpa",
    email: "m.brooks@adskill.com",
    role: "Accountant",
    status: "Active",
    whatsapp: "+12125550199",
    phone: "+1 (212) 555-0199",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    initials: "MB",
    department: "Finance & Billing",
    createdAt: "Mar 10, 2025",
    lastActive: "1 hour ago",
    assignedCasesCount: 84,
    twoFactorEnabled: true,
    bio: "Head Accountant managing trust accounting, escrow reconciliations, and Stripe invoices.",
    activityLogs: [
      {
        id: "act-6",
        action: "Verified Offline Bank Wire",
        target: "Invoice #INV-2026-0491 ($3,000)",
        timestamp: "Today at 9:00 AM",
        ipAddress: "74.125.21.19",
      },
      {
        id: "act-7",
        action: "Generated Monthly Revenue Reconciliation",
        target: "August 2026 Financials",
        timestamp: "Sep 01, 2026 at 6:00 PM",
        ipAddress: "74.125.21.19",
      },
    ],
  },
  {
    id: "4",
    userId: "USR-2026-104",
    name: "Elena Rostova",
    username: "@elena_r",
    email: "elena.rostova@adskill.com",
    role: "Consultant",
    status: "Active",
    whatsapp: "+491512345678",
    phone: "+49 151 2345678",
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    initials: "ER",
    department: "European Immigration",
    createdAt: "May 04, 2025",
    lastActive: "3 hours ago",
    assignedCasesCount: 29,
    twoFactorEnabled: false,
    bio: "European Union immigration specialist handling EU Blue Card and skilled tech talent.",
    activityLogs: [
      {
        id: "act-8",
        action: "Uploaded Employment Contract",
        target: "Client: Elena Rostova",
        timestamp: "Yesterday at 2:20 PM",
        ipAddress: "91.198.174.192",
      },
    ],
  },
  {
    id: "5",
    userId: "USR-2026-105",
    name: "Seif Edwards",
    username: "@seif_support",
    email: "seif.e@adskill.com",
    role: "Support",
    status: "Active",
    whatsapp: "+61411234567",
    phone: "+61 411 234 567",
    avatarUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    initials: "SE",
    department: "Customer Success",
    createdAt: "Jun 18, 2025",
    lastActive: "Yesterday",
    assignedCasesCount: 52,
    twoFactorEnabled: true,
    bio: "Support lead coordinating applicant documents, intake forms, and WhatsApp helpdesk tickets.",
    activityLogs: [
      {
        id: "act-9",
        action: "Resolved WhatsApp Ticket #WA-881",
        target: "Client: Johnathan Doe",
        timestamp: "Yesterday at 11:15 AM",
        ipAddress: "139.130.4.5",
      },
    ],
  },
  {
    id: "6",
    userId: "USR-2026-106",
    name: "Arjun Sharma",
    username: "@arjun_s",
    email: "arjun.sharma@example.com",
    role: "Client",
    status: "Active",
    whatsapp: "+919820012345",
    phone: "+91 98200 12345",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    initials: "AS",
    department: "Client Portal User",
    createdAt: "Jan 12, 2026",
    lastActive: "2 days ago",
    assignedCasesCount: 1,
    twoFactorEnabled: true,
    bio: "Client enrolled in Canada Express Entry Federal Skilled Worker program.",
    activityLogs: [
      {
        id: "act-10",
        action: "Paid Milestone Installment #2",
        target: "Invoice #INV-2026-0819 ($1,500)",
        timestamp: "Jan 12, 2026 at 3:10 PM",
        ipAddress: "103.21.244.0",
      },
    ],
  },
  {
    id: "7",
    userId: "USR-2026-107",
    name: "Fatima Al-Zahra",
    username: "@fatima_z",
    email: "fatima.z@example.com",
    role: "Client",
    status: "Pending",
    whatsapp: "+97143329012",
    phone: "+971 4 332 9012",
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    initials: "FA",
    department: "Client Portal User",
    createdAt: "Dec 20, 2025",
    lastActive: "Pending Invite",
    assignedCasesCount: 1,
    twoFactorEnabled: false,
    bio: "Start-Up Visa applicant awaiting portal registration verification.",
    activityLogs: [],
  },
  {
    id: "8",
    userId: "USR-2026-108",
    name: "Marcus Vance",
    username: "@marcus_v",
    email: "marcus.vance@adskill.com",
    role: "Admin",
    status: "Suspended",
    whatsapp: "+14155552345",
    phone: "+1 (415) 555-2345",
    avatarUrl:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    initials: "MV",
    department: "Operations",
    createdAt: "Jul 22, 2025",
    lastActive: "Aug 14, 2026",
    assignedCasesCount: 0,
    twoFactorEnabled: false,
    bio: "Former regional operations coordinator. Account suspended pending audit review.",
    activityLogs: [
      {
        id: "act-11",
        action: "Account Suspended by Super Admin",
        target: "Policy Compliance",
        timestamp: "Aug 14, 2026 at 10:00 AM",
        ipAddress: "192.168.1.10",
      },
    ],
  },
];
